### ISSUE TITLE
issues with transparent objects

### ISSUE THREAD

**Issue by robertoranon** [jean-moreno/EdgeDetect-PostProcessingUnity#1]
Hi,

 thanks for porting the effect!

The only issue I have is that it makes transparent objects disappear - as if they are fully transparent. The old image effect had a field (ImageEffectOpaque) to control whether the effect was applied before or after transparent objects rendering (https://docs.unity3d.com/550/Documentation/Manual/script-EdgeDetectEffectNormals.html). Is it possible to do the same?

Thanks!

**Comment by jean-moreno** [comment]
It should work like it did in previous Unity versions now.
