### ISSUE TITLE
Edge detection effects that rely on Camera Depth + Normals texture don't work with scriptable render pipeline

### ISSUE THREAD

**Issue by Hindi** [jean-moreno/EdgeDetect-PostProcessingUnity#13]
Thanks for the great work.

Using Unity 2018.3.0f2 Personal, the following warning shows up when I select Triangle Depth Normals:
> Edge detection effects that rely on Camera Depth + Normals texture don't work with scriptable render pipeline

**Comment by JeanCyclone** [comment]
Does that happen using the Lightweight or High-Definition pipelines? Or just with the legacy renderer?

**Comment by jean-moreno** [comment]
Closing this for now, will need more info.
This message is expected when using either LWRP or HDRP; it should not happen with the legacy renderer.
If it does let me know and I'll reopen the issue.
