### ISSUE TITLE
Destroys Post Processing in Standalone Build

### ISSUE THREAD

**Issue by dog199200** [jean-moreno/EdgeDetect-PostProcessingUnity#2]
Hello,

So I just updated Post Processing v2, and found that this script is killing the Post Processing Stack on a standalone build. The effects work perfectly fine in the Editor. It does not matter where in the stack it is, the problem still exists. It also doesn't matter is nothing at all is selected, as long as the effect is either set to "on" or checked enabled it will break the entire stack.

Edit: One more thing to note: It can be the only effect in the stack and it breaks the post processing.

**Comment by Lestat** [comment]
I have the same problem

**Comment by Lestat** [comment]
@dog199200 were you able to find a workaround?

**Comment by dog199200** [comment]
No, I was not. I just ended up removing it entirely until something can get fixed...

**Comment by Lestat** [comment]
well, I used the legacy edge detection script directly instead of using this add on.

**Comment by jean-moreno** [comment]
@Lestat @dog199200 Can you try to add the `EdgeDetectNormalsPostProcess.shader` file to the *"Always Included Shaders"* in *Edit > Project Settings > Graphics*?
This seem to have worked for me.
I'll see if there's a way to prevent doing that for the effect to work properly though.

**Comment by Lestat** [comment]
Will test, although maybe im better using the legacy edge detection script directly, I think is less risky than rely on this addon :p

**Comment by Lestat** [comment]
Well, it works now :p

**Comment by dog199200** [comment]
I am still unable to get it to work.

![inspector1](https://user-images.githubusercontent.com/16627111/33178528-50b95f8a-d01b-11e7-97c8-0d2ae556735c.png)
![inspector2](https://user-images.githubusercontent.com/16627111/33178529-5110f84e-d01b-11e7-9915-55b6b141606e.png)
![inspector3](https://user-images.githubusercontent.com/16627111/33178550-679439dc-d01b-11e7-8276-e8413beaa673.png)

**Comment by Daventor** [comment]
I must add:
 #pragma glsl 
to avoid an error whem make the build, but now this works fine.

**Comment by jean-moreno** [comment]
@dog199200 please try the latest version, I moved the shader to the Resource folder. If it still doesn't work, please let me know which version of Unity you are using and the target platform.

@Daventor that sounds weird, `#pragma glsl` should have no effect anymore since Unity 5! (see: https://docs.unity3d.com/Manual/SL-ShaderPrograms.html)
