### ISSUE TITLE
Edge color

### ISSUE THREAD

**Issue by Frou-HOS** [jean-moreno/EdgeDetect-PostProcessingUnity#3]
Hello Jean,
Thx for this awsome work !
I just want to know, how it's possible to change edge color ?
I'm a newbie in shader but, i will do my best for understand.

**Comment by Frou-HOS** [comment]
I just found this shader realy similar I will mix it : 
https://forum.unity.com/threads/image-effect-edge-detect-normals-colours-rel.310280/

**Comment by Frou-HOS** [comment]
Ok it's done for me :)
I'm not familiar with github and pull request but I will try to do it. 
Hope it will be usefull for somebody

**Comment by jean-moreno** [comment]
I don't think that's an issue, but rather a feature request, so I'm closing it.

I'll look into your pull request when I have some time (I'm not familiar with GitHub either so the process is a little tedious to me). I briefly read it and it looked fine, minor some syntax things and an if() condition to remove in the shader.
