### ISSUE TITLE
Some effects don't work with Lighweight Pipeline SRP

### ISSUE THREAD

**Issue by LemuriaOnline** [jean-moreno/EdgeDetect-PostProcessingUnity#5]
Not working with ScriptableRenderPipeline Lightweight + PostProcessing v2 + Unity 2018.1.0b10 

The game view Appears BLACK and the edges starts to appear when I slide the edges only slider to the right but with white background.

**Comment by jean-moreno** [comment]
I haven't looked into SRP much yet, and I can't find any information about how it is supposed to interact with Post Processing.
I'll wait for Unity 2018.1 to be out of beta before looking into it though, when I'll have time.
In the meantime, let me know if you find anything on that subject!

**Comment by jean-moreno** [comment]
It works on my end with the following:
- Unity 2018.1.0f2
- Post Processing 2.0.7-preview
- Lightweight Render Pipeline 1.1.10-preview

However the effects based on depth + normals don't work, because the `_CameraDepthNormalsTexture` doesn't seem to be generated by the Lightweight Pipeline.

**Comment by jean-moreno** [comment]
The editor will show a warning box for the unavailable effects when using SPRs.
There are no signs from Unity that they will render the CameraDepthNormals texture in SRPs as they do in Legacy, so I'm closing this issue for now.

**Comment by amartinez1660** [comment]
It would be nice if this were to be stated on some documents as it is really hard to find why something is not working.
Spent hours trying to use _CameraDepthNormalsTexture on a shader without real feedback of why it wasn't working, just a black screen. Overriding GetCameraFlags(), assigning scripts to the camera like in the legacy days, etc yields no warning, feedbacks or errors.

My bad: it's actually here: https://docs.unity3d.com/Packages/com.unity.render-pipelines.lightweight@6.7/manual/lwrp-builtin-feature-comparison.html
