### ISSUE TITLE
Path issue with unity 2018.1

### ISSUE THREAD

**Issue by kefniark** [jean-moreno/EdgeDetect-PostProcessingUnity#6]
## Description
I tried to use this effect with:
* new unity 2018.1
* new post processing stack provided through package manager
* no RP, the standard legacy rendering

But it doesn't work.
After few minutes I finally managed to get a proper error:
```
failed to open source file: ‘Assets/PostProcessing/Shaders/StdLib.hlsl’
```

It's just the path to **stdlib.hlsl** which is not the same anymore.
```
#include "PostProcessing/Shaders/StdLib.hlsl"
```
With this small fix, it works 👍 
![image](https://user-images.githubusercontent.com/4903529/39924815-417f2698-5564-11e8-803f-6de7475fa7dd.png)

P.S. Thanks a lot for this repo, I was about to write exactly the same :)

**Comment by jean-moreno** [comment]
Thanks for the fix, I've pushed it to the repo!
d16b816189ad6b8835c9bd5c414cf73f73c4248e
