### ISSUE TITLE
Effect looks broken on SRP 2

### ISSUE THREAD

**Issue by Rockylars** [jean-moreno/EdgeDetect-PostProcessingUnity#7]
- Unity 2018.2.0f2
- SRP 2.0.5-pre
- LWRP 2.0.5-pre
- PPS 2.0.8-pre

The new Unity release of 2018's will cause the defined Background Color to be put over the skybox and bloom, its an effect that cant be fully disabled, sliding the Edges only factor around will in-/decrease its effect.

Replacing the PostProcessEvent definition above the EdgeDetectPostProcessing class with BeforeStack will fix it, as BeforeTransparent now no longer handles it properly, this will cause issues with the intent of drawing lines on top of transparent objects.

https://imgur.com/MXSEnPn
https://imgur.com/tZcI623

**Comment by jean-moreno** [comment]
I looked into this today, and it seems to be an issue with Post Processing & LWRP: I also get wrong results when using the example custom effects from (Post Processing's wiki](https://github.com/Unity-Technologies/PostProcessing/wiki/Writing-Custom-Effects).
For some reason the color returned by the main image in the post effect is wrong when using the *BeforeTransparent* injection through Post Processing.

I'll leave it at *BeforeTransparent* for now though, as this works with the legacy rendering pipeline and LWRP is still in preview mode.

**Comment by jean-moreno** [comment]
I've submitted an issue on Post Processing's GitHub: https://github.com/Unity-Technologies/PostProcessing/issues/653

**Comment by Rockylars** [comment]
- Unity 2018.2.6f1
- RPCL (SRP's new name) 3.0.0-pre
- LWRP 3.0.0-pre
- PPS 2.0.12-pre

It appears the Gizmo's are partially broken with the LWRP as well for a lot of users including our project, and will be fixed by 2018.3, making them either not appear at all or in our case, flicker whenever we have a Post Processing Layer assigned to our camera, even if the Post Processing Volume doesnt exist, so i too would say that you should wait.

The issue still persists, with _BeforeTransparent _ now causing a ghost effect that removes everything behind the outlined object and the object itself, _AfterStack_ will give a much brighter effect, as if it doubles certain coloring and _BeforeStack_ still works fine.

**Comment by jean-moreno** [comment]
I've updated the effect so that the three injection points are available to the user, this way it can work with all three renderers (legacy, LWRP, HDRP).
Some effects are still unavailable for SPRs and a warning box will inform the user.

For this particular issue, use the "Before Stack" injection rather than "Before Transparent".
